minimum_pre_commit_version: 4.3.0
default_install_hook_types:
  - pre-commit
  - pre-push
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: '3e8a8703264a2f4a69428a0aa4dcb512790b2c8c'  # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md,markdown
  - repo: https://github.com/andreoliwa/nitpick
    rev: '3ba97e5d57882cca6ef1eccaae683753c8a26630'  # frozen: v0.38.1
    hooks:
      - id: nitpick
  - repo: https://github.com/codespell-project/codespell
    rev: '63c8f8312b7559622c0d82815639671ae42132ac'  # frozen: v2.4.1
    hooks:
      - additional_dependencies:
          - tomli ; python_version < '3.11'
        id: codespell
  - repo: https://github.com/commitizen-tools/commitizen
    rev: '2e4f4b26b5b0a0c0ebc660c1f78aca1e28d912bd'  # frozen: v4.11.1
    hooks:
      - id: commitizen
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: '4380fbb73a154b5f5624794c1c78d9719ccc860f'  # frozen: v2.16.0
    hooks:
      - id: pretty-format-toml
        args:
          - --autofix
          - --no-sort
          - --trailing-commas
          - --indent
          - '4'
          - --inline-comment-spaces
          - '1'
