[".cz.toml".tool.commitizen]
name = "cz_conventional_commits"
version_scheme = "semver2"
version_provider = "scm"
update_changelog_on_bump = true
major_version_zero = true
annotated_tag = true

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/commitizen-tools/commitizen"
hooks = [{id = "commitizen"}]
