[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = [
    "black.toml",
    "commitizen.toml",
    "pre-commit.toml",
    "coverage.toml",
    "autoflake.toml",
    "common.toml",
    "styles/common-python/common-python.toml",
]

["pyproject.toml".tool.isort]
line_length = 80
profile = "black"
float_to_top = true

["pyproject.toml".tool.flynt]
transform-concats = true
transform-joins = true
line-length = 120
aggressive = true
