[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = ["pre-commit.toml"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/asottile/pyupgrade"
[[".pre-commit-config.yaml".repos.hooks]]
id = "pyupgrade"
args = ["--py311-plus"]
