["pyproject.toml".tool.mypy]
ignore_missing_imports = true
show_error_codes = true
warn_unused_ignores = true
warn_unused_configs = true
warn_redundant_casts = true
enable_error_code = [
    "deprecated",
]

# "exhaustive-match",
# "explicit-override",
# "ignore-without-code",
# "mutable-override",
# "possibly-undefined",
# "redundant-expr",
# "redundant-self",
# "truthy-bool",
# "truthy-iterable",
# "unimported-reveal",
# "unused-awaitable",
# "unused-ignore",
