[nitpick.styles]
include = [
    "../mypy/mypy-3.9.toml",
]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/asottile/pyupgrade"
hooks = [{id = "pyupgrade", args = ["--py39-plus"]}]

["pyproject.toml".project]
requires-python = ">=3.9"
