[nitpick.styles]
include = [
    "../mypy/mypy-3.10.toml",
]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/asottile/pyupgrade"
hooks = [{id = "pyupgrade", args = ["--py310-plus"]}]

["pyproject.toml".project]
requires-python = ">=3.10"
